name: Generate dwm keymaps file with github workflows only if config.h is changed
on:
  push:
    paths:
      - 'config.h'
jobs:
  # this workflow contains a single job called "run dwm keymaps script"
  build:
    # type of the runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # checkout repo under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # runs a single command / script
      - name: run dwm keymaps script
        run: sh ./docs/getdwmkeys.sh config.h markdown

      # run a multiline script
      - name: Multiline Script
        run: |
          echo "./docs/getdwmkeys.sh executed!"
          ls -lart

      # Move the generated files into output folder
      - name: move to dir docs
        run: |
          mv keys.md ./docs/

      # commit the output folder
      - name: Commit files
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add ./docs/
          git commit -m "add created keys.md file"

      # push the output folder to your repo
      - name: Push changes
        uses: ad-m/github-push-action@master

